import type { Complaint } from "./types";

/* ============================================
   PRE-LOADED DEMO COMPLAINTS
   ============================================ */

const now = new Date();
const hoursAgo = (h: number) => new Date(now.getTime() - h * 3600 * 1000).toISOString();
const daysAgo = (d: number) => new Date(now.getTime() - d * 86400 * 1000).toISOString();

export const DEMO_COMPLAINTS: Complaint[] = [
  {
    id: "NV-2026-XK92R",
    pin: "482917",
    rawText: "There has been no water supply in ward 14 for the last three days. More than 200 families are affected. We have complained to the local office but nobody is listening. Children are falling sick because of dirty water from the well.",
    category: "water",
    priority: "high",
    status: "action_taken",
    reportingMode: "self",
    summary: "No water supply in Ward 14 for 3 days. 200+ families affected, children falling sick from contaminated well water.",
    location: "Ward 14",
    affectedPeople: 200,
    mediaUrls: [],
    createdAt: daysAgo(4),
    updatedAt: hoursAgo(6),
    assignedTo: "off_001",
    communityVotes: 47,
    validatorEndorsements: 3,
    genuinenessScore: 85,
    approved: true,
    escalationLevel: 1,
    timeline: [
      { id: "t1", status: "submitted", timestamp: daysAgo(4), note: "Complaint submitted via voice", actor: "Citizen", actorRole: "citizen" },
      { id: "t2", status: "verified", timestamp: daysAgo(3.5), note: "Verified by 3 community validators", actor: "Community", actorRole: "validator" },
      { id: "t3", status: "assigned", timestamp: daysAgo(3), note: "Assigned to Ward Officer Rajesh Kumar", actor: "System", actorRole: "system" },
      { id: "t4", status: "under_review", timestamp: daysAgo(2), note: "Site inspection scheduled", actor: "Rajesh Kumar", actorRole: "official" },
      { id: "t5", status: "action_taken", timestamp: hoursAgo(6), note: "Water tanker dispatched. Pipeline repair in progress.", actor: "Rajesh Kumar", actorRole: "official" },
    ],
    proofOfAction: [
      { id: "p1", type: "before", note: "Dry taps in ward 14 — no water for 3 days", uploadedBy: "Rajesh Kumar", uploadedAt: daysAgo(2), imageUrl: "" },
      { id: "p2", type: "after", note: "Water tanker supplied. Pipeline repair crew deployed.", uploadedBy: "Rajesh Kumar", uploadedAt: hoursAgo(6), imageUrl: "" },
    ],
  },
  {
    id: "NV-2026-MP3T8",
    pin: "739264",
    rawText: "The main road near the government school has a huge pothole. Two people got injured last week. The road was supposed to be repaired three months ago but nothing has happened. It is very dangerous especially at night.",
    category: "roads",
    priority: "high",
    status: "resolved",
    reportingMode: "self",
    summary: "Large pothole near government school on main road. Two injuries reported. Road repair pending for 3 months.",
    location: "Near Government School",
    affectedPeople: 500,
    mediaUrls: [],
    createdAt: daysAgo(10),
    updatedAt: daysAgo(1),
    assignedTo: "off_001",
    communityVotes: 89,
    validatorEndorsements: 5,
    genuinenessScore: 95,
    approved: true,
    escalationLevel: 0,
    timeline: [
      { id: "t1", status: "submitted", timestamp: daysAgo(10), note: "Complaint submitted", actor: "Citizen", actorRole: "citizen" },
      { id: "t2", status: "verified", timestamp: daysAgo(9), note: "89 community members confirmed", actor: "Community", actorRole: "validator" },
      { id: "t3", status: "assigned", timestamp: daysAgo(8), note: "Assigned to Ward Officer", actor: "System", actorRole: "system" },
      { id: "t4", status: "under_review", timestamp: daysAgo(6), note: "Engineer site visit completed", actor: "Public Works", actorRole: "official" },
      { id: "t5", status: "action_taken", timestamp: daysAgo(3), note: "Road repair started", actor: "Public Works", actorRole: "official" },
      { id: "t6", status: "resolved", timestamp: daysAgo(1), note: "Pothole filled and road resurfaced", actor: "Public Works", actorRole: "official" },
    ],
    proofOfAction: [
      { id: "p1", type: "before", note: "Massive pothole near school gate", uploadedBy: "Engineer Team", uploadedAt: daysAgo(6) },
      { id: "p2", type: "after", note: "Road fully repaired and resurfaced", uploadedBy: "Engineer Team", uploadedAt: daysAgo(1) },
    ],
  },
  {
    id: "NV-2026-QW7L5",
    pin: "156832",
    rawText: "The BDO office is asking for five hundred rupees bribe for issuing a caste certificate. My father went three times but they keep asking for money. Without the certificate my college admission is stuck.",
    category: "corruption",
    priority: "critical",
    status: "under_review",
    reportingMode: "anonymous",
    summary: "BDO office demanding ₹500 bribe for caste certificate. Multiple visits, continued extortion. College admission blocked.",
    location: "BDO Office",
    affectedPeople: 50,
    mediaUrls: [],
    createdAt: daysAgo(2),
    updatedAt: hoursAgo(12),
    assignedTo: "off_003",
    communityVotes: 156,
    validatorEndorsements: 8,
    genuinenessScore: 92,
    approved: true,
    escalationLevel: 0,
    timeline: [
      { id: "t1", status: "submitted", timestamp: daysAgo(2), note: "Anonymous complaint submitted", actor: "Anonymous", actorRole: "citizen" },
      { id: "t2", status: "verified", timestamp: daysAgo(1.5), note: "156 community votes confirming similar experience", actor: "Community", actorRole: "validator" },
      { id: "t3", status: "assigned", timestamp: daysAgo(1), note: "Escalated to District Collector", actor: "System", actorRole: "system" },
      { id: "t4", status: "under_review", timestamp: hoursAgo(12), note: "Investigation initiated by Anti-Corruption Cell", actor: "District Collector", actorRole: "official" },
    ],
    proofOfAction: [],
  },
  {
    id: "NV-2026-RT4N9",
    pin: "284571",
    rawText: "The ration shop owner is not giving full wheat quota. He marks attendance but gives only half. This has been happening for three months. Many families are not getting enough food.",
    category: "ration",
    priority: "high",
    status: "assigned",
    reportingMode: "proxy",
    proxyReporter: { name: "Sunita Bai", relationship: "NGO Volunteer", organization: "Jan Seva Foundation" },
    summary: "Ration dealer distributing half quota while marking full attendance. 3 months of systematic denial. Multiple families affected.",
    location: "Ward 7 Ration Shop",
    affectedPeople: 150,
    mediaUrls: [],
    createdAt: daysAgo(1),
    updatedAt: hoursAgo(8),
    communityVotes: 34,
    validatorEndorsements: 2,
    genuinenessScore: 78,
    approved: true,
    escalationLevel: 0,
    timeline: [
      { id: "t1", status: "submitted", timestamp: daysAgo(1), note: "Filed by proxy through NGO volunteer", actor: "Sunita Bai (Jan Seva Foundation)", actorRole: "citizen" },
      { id: "t2", status: "verified", timestamp: hoursAgo(18), note: "Verified by 2 trusted validators", actor: "Validators", actorRole: "validator" },
      { id: "t3", status: "assigned", timestamp: hoursAgo(8), note: "Assigned to Food Inspector", actor: "System", actorRole: "system" },
    ],
    proofOfAction: [],
  },
  {
    id: "NV-2026-KL8M2",
    pin: "917345",
    rawText: "There is garbage piled up near the community hall for over two weeks. It is causing bad smell and mosquitoes. Many children in the area have fever. The sweeper has not come even once this month.",
    category: "sanitation",
    priority: "medium",
    status: "verified",
    reportingMode: "self",
    summary: "Garbage accumulation near community hall for 2+ weeks. Mosquito breeding, children falling ill. Municipal sweeper absent.",
    location: "Near Community Hall",
    affectedPeople: 80,
    mediaUrls: [],
    createdAt: hoursAgo(36),
    updatedAt: hoursAgo(24),
    communityVotes: 22,
    validatorEndorsements: 1,
    genuinenessScore: 65,
    approved: true,
    escalationLevel: 0,
    timeline: [
      { id: "t1", status: "submitted", timestamp: hoursAgo(36), note: "Complaint submitted", actor: "Citizen", actorRole: "citizen" },
      { id: "t2", status: "verified", timestamp: hoursAgo(24), note: "Verified by community validator", actor: "Validator", actorRole: "validator" },
    ],
    proofOfAction: [],
  },
  {
    id: "NV-2026-WS5P7",
    pin: "638192",
    rawText: "A woman in our village is being beaten by her husband regularly. She is afraid to go to the police. Her neighbors hear screaming at night. She has two small children. Please help.",
    category: "abuse",
    priority: "critical",
    status: "assigned",
    reportingMode: "proxy",
    proxyReporter: { name: "Meera Devi", relationship: "Neighbor", organization: "" },
    summary: "Domestic violence case — woman regularly beaten, afraid to report. Two small children involved. Urgent intervention needed.",
    affectedPeople: 4,
    mediaUrls: [],
    createdAt: hoursAgo(8),
    updatedAt: hoursAgo(4),
    assignedTo: "off_004",
    communityVotes: 12,
    validatorEndorsements: 2,
    genuinenessScore: 88,
    approved: true,
    escalationLevel: 0,
    timeline: [
      { id: "t1", status: "submitted", timestamp: hoursAgo(8), note: "Proxy complaint by neighbor", actor: "Meera Devi", actorRole: "citizen" },
      { id: "t2", status: "verified", timestamp: hoursAgo(6), note: "Urgency verified — critical priority", actor: "System", actorRole: "system" },
      { id: "t3", status: "assigned", timestamp: hoursAgo(4), note: "Assigned to Women's Cell Head", actor: "System", actorRole: "system" },
    ],
    proofOfAction: [],
  },
  {
    id: "NV-2026-BN3J6",
    pin: "451289",
    rawText: "Fake seeds were sold to farmers in our block by the government seed depot. The crops did not grow at all. More than 30 farmers have lost their entire season. The depot manager is not responding.",
    category: "corruption",
    priority: "critical",
    status: "submitted",
    reportingMode: "self",
    summary: "Government seed depot sold fake seeds. 30+ farmers lost entire season crop. Depot manager unresponsive.",
    location: "Block Seed Depot",
    affectedPeople: 30,
    mediaUrls: [],
    createdAt: hoursAgo(2),
    updatedAt: hoursAgo(2),
    communityVotes: 5,
    validatorEndorsements: 0,
    genuinenessScore: 30,
    approved: true,
    escalationLevel: 0,
    timeline: [
      { id: "t1", status: "submitted", timestamp: hoursAgo(2), note: "Complaint submitted", actor: "Citizen", actorRole: "citizen" },
    ],
    proofOfAction: [],
  },
  {
    id: "NV-2026-FG9H1",
    pin: "762843",
    rawText: "The streetlights on the main road in sector 5 have been broken for over a month. Three chain snatching incidents happened in the dark. Women are afraid to go out after 7pm. Nobody from the corporation is fixing this.",
    category: "safety",
    priority: "high",
    status: "submitted",
    reportingMode: "anonymous",
    summary: "Broken streetlights in Sector 5 for 1+ month. Three chain snatching incidents. Women unsafe after dark.",
    location: "Sector 5, Main Road",
    affectedPeople: 300,
    mediaUrls: [],
    createdAt: hoursAgo(5),
    updatedAt: hoursAgo(5),
    communityVotes: 18,
    validatorEndorsements: 0,
    genuinenessScore: 45,
    approved: true,
    escalationLevel: 0,
    timeline: [
      { id: "t1", status: "submitted", timestamp: hoursAgo(5), note: "Anonymous complaint submitted", actor: "Anonymous", actorRole: "citizen" },
    ],
    proofOfAction: [],
  },
];

/** Loads demo data into localStorage if empty */
export function loadDemoData(): Complaint[] {
  return DEMO_COMPLAINTS;
}
